// A short, visitor-facing list of recent site updates, shown in the
// "What's New" panel on /feed. Kept separate from CHANGELOG.md, which is
// written for Taylor (second person, technical detail like migration file
// names) — this one is written for anyone using the site. Add a new entry
// here (most recent first) whenever something user-visible ships; no need
// to log every internal fix.
//
// `detail` is optional, longer follow-up text shown when someone clicks
// an entry to expand it (see components/WhatsNewList.jsx) — a bit more
// of the "why" or "how" behind the one-line `body`, still in plain,
// user-facing language rather than CHANGELOG.md's technical detail.
// Entries without a `detail` just show `body` on click too, so it's
// safe to leave off for something the one-liner already fully covers.
export const WHATS_NEW = [
  {
    date: '2026-09-01',
    title: 'Redesigned: a real dashboard sidebar',
    body: 'Collection insights, Your Wrapped, Collection appraisal, Upcoming releases, Full release catalogue, Print labels, and API access all used to be one click deep inside a "More actions" menu — they now live in a real sidebar, visible on every dashboard page.',
    detail: 'The sidebar is grouped into My Collection, Insights & reports, Utilities, and Account, with whatever page you\'re on highlighted so you always know where you are. On a phone it slides in from a toggle button instead of taking up screen space by default. The old "More actions" dropdown is gone — Refresh all prices and Settings are now plain buttons on the dashboard toolbar.',
  },
  {
    date: '2026-09-01',
    title: 'New: Upcoming Releases, a calendar of what\'s coming',
    body: 'A new Upcoming Releases page shows what\'s still coming for the game franchises and comic series you already own something from, grouped by month, with a running spend total from prices you type in yourself.',
    detail: 'Find it in the sidebar under Insights & reports > Upcoming releases. Covers games and comics for now — release dates come from IGDB and Comic Vine and refresh weekly, so a series you\'ve just started collecting can take up to a week to show up. There\'s no price data available for anything that hasn\'t released yet, so the "expected price" per item is your own guess, remembered on this device.',
  },
  {
    date: '2026-09-01',
    title: 'New: adjustable text size',
    body: 'A "Text" control next to the Dark/Light switch in the navbar now offers Normal, Large, and Larger — scales the whole page, not just body copy.',
    detail: 'Especially useful in the wrapped app, where iOS\'s own system-level "Larger Text" setting doesn\'t reach web content. Your choice is remembered on this device.',
  },
  {
    date: '2026-09-01',
    title: 'New: write a review for any item',
    body: 'The page for any game, comic, or collectible now has a Reviews section — a star rating plus your own written thoughts, separate from your private personal rating, visible to anyone browsing that item.',
    detail: 'Find it on any item\'s page (click through from a card, or search for a title). You can review anything you\'ve logged as owned — one review per item, edit or delete it any time. Reviews from private profiles stay private, same as everywhere else on the site.',
  },
  {
    date: '2026-09-01',
    title: 'New: personal access tokens for your own collection',
    body: 'Generate a token and pull your collection as JSON into a script, spreadsheet, or your own dashboard — no more exporting a CSV by hand.',
    detail: 'Find it in the sidebar under Utilities > API access. Two endpoints, both read-only and scoped to your own data: your basic account info, and your full collection with optional type/ownership filters. Free, rate-limited to 60 requests a minute per token, and a token can be revoked any time.',
  },
  {
    date: '2026-08-30',
    title: 'Print QR labels for your shelf',
    body: 'A new "Print labels" page lays out a small QR sticker per item on standard address label sheets — scan one to jump straight to that item on your phone.',
    detail: 'Pick which owned items to include and it prints 30 per sheet, sized for Avery 5160 (or compatible) label paper. Handy if you box up and store a physical collection and want a fast way to look an item back up.',
  },
  {
    date: '2026-08-30',
    title: 'New: 8 more Shelf Life trophies to earn',
    body: 'New badges for owning 20 items on one platform, 10 genres, or at least one of every collectible type, plus new ones for tagging, writing notes, attaching condition photos, marking items for sale, and marking items sold. Platinum Shelf now takes 8 more to earn, same as every past trophy addition.',
  },
  {
    date: '2026-08-30',
    title: 'New: "Wishlist matches" panel on the dashboard',
    body: 'A new panel (inside Tools > Insights) shows which public collectors you follow already own something on your wishlist — and flags when they own more than one, a hint they might have a spare worth asking about.',
  },
  {
    date: '2026-08-30',
    title: 'New: opt-in weekly activity digest email',
    body: 'A new "Email me a weekly activity digest" checkbox in Settings > Data sends a Sunday email with your own week (what you added, completed, rated, or earned a trophy for) plus a rundown of what the public collectors you follow have been up to. Off by default, and it skips itself entirely on a quiet week with nothing to report.',
  },
  {
    date: '2026-08-30',
    title: 'Leaderboard "Most valuable" now shows a converted figure, in your currency',
    body: 'The ranking itself was already fair across currencies — a €5,000 collection correctly outranking a $6,000 one, say — but there was no way to see why. The podium now shows a converted amount alongside a collector\'s own-currency total, in whatever currency you\'ve picked in Settings, whenever it\'s different from theirs.',
  },
  {
    date: '2026-08-30',
    title: 'New: browse a platform\'s full release list',
    body: 'A new "Full release catalogue" page (find it in the sidebar under Utilities, or click "See full release list" on an active "Browse by system" tile) lets you pick a platform — PlayStation 2, Switch, whatever — and see every major game released for it, greyed out except what you\'ve already logged. Handy for spotting real gaps in a system you\'re actively completing.',
    detail: 'Search within the list to jump straight to a title. Covers main game releases only (not DLC/expansions/bundles), so it stays a clean checklist rather than a cluttered one.',
  },
  {
    date: '2026-08-29',
    title: 'New: "See full series" now works for Vinyl, CDs, DVDs, VHS, and Books',
    body: 'Editing one of these now shows a "See full series" button, same as games/comics/trading cards/Funko Pops already had — it groups everything by the same artist, director, or author that Shelf Life collectors have logged, so you can see the rest of a discography, filmography, or bibliography you might be missing.',
    detail: 'Like Funko Pops, this pulls from what other Shelf Life collectors have actually logged rather than a real outside catalog — there\'s no free public API for this kind of series data the way there is for games/comics/trading cards. Consoles don\'t get this button: there\'s no natural "series" for a console the way there is an artist\'s albums or an author\'s books.',
  },
  {
    date: '2026-08-29',
    title: 'A fresh coat of paint: gold & mint, softer cards, a real Trophy Case',
    body: 'The site\'s dark theme stays the same, but the accent colors are new — warm gold and mint instead of the old purple/teal — cards and pills got rounder corners, missing cover art now shows a clean category icon instead of a broken-image look, and the Trophy Case got a real "velvet panel and medallions" redesign with locked trophies showing a lock icon.',
    detail: 'Also new: a horizontal category-filter rail above your collection on the dashboard, a faint mosaic of your own real cover art behind your public profile header (with a "Public shelf"/"Private" badge next to your name), and a small illustration on the empty-collection welcome screen. Nothing about how any of these work changed — same cards, same Trophy Case data, same public/private rules — this round was entirely visual.',
  },
  {
    date: '2026-08-28',
    title: 'New: "Quick add (type it)" — log an item in one typed line',
    body: 'A new option in the dashboard\'s "+ Add Item" menu lets you just type something like "fifa 06 on ps2 CIB $8 today" — it picks out the title, price, date, platform, and completeness as you type, shows you what it understood, and hands it to the normal Add form so you can double-check before saving.',
    detail: 'It\'s a best-effort parser, not a real language model — it looks for a leading verb ("got"/"bought"/"logged"/etc.), a trailing "today"/"yesterday", a "$N" price, a platform mention ("on ps2", "for Switch"), and a completeness mention ("CIB", "loose", "box only"), then treats what\'s left as the title. Nothing saves automatically: "Continue" opens the same Add form you\'d normally fill out, pre-filled, so a wrong guess is just something to fix before you hit Save.',
  },
  {
    date: '2026-08-28',
    title: 'Pokémon master sets now show every real print variant',
    body: '"See master set" used to only expand a card into Normal/Reverse Holo/Holo tiles once you already owned one of its variants. Sets you\'ve logged cards from now build up a real, complete variant checklist behind the scenes, so you can see prints you don\'t have yet — not just confirm the ones you do.',
  },
  {
    date: '2026-08-28',
    title: 'New: real master sets for Magic: The Gathering',
    body: '"See master set" now works for Magic cards, not just Pokémon — a genuine per-set checklist (including foil and etched foil prints) instead of only showing what other Shelf Life collectors happen to have logged.',
  },
  {
    date: '2026-08-27',
    title: 'New: opt-in monthly email backup',
    body: 'A new "Email me a monthly backup" checkbox in Settings > Data sends you the same collection CSV and full data export you can already download on demand, automatically, once a month. Off by default.',
  },
  {
    date: '2026-08-27',
    title: 'Fixed: broken cover images now show a placeholder everywhere',
    body: "A dead cover-art link used to show the browser's generic broken-image icon in a few spots — search results, the item detail view, master-set grids, and public lists. Now it shows the same clean placeholder covers already use elsewhere.",
  },
  {
    date: '2026-08-27',
    title: 'Fixed: keyboard tabbing through the leaderboard podium',
    body: 'If you navigate by keyboard, tabbing through the top-3 podium now goes left to right the way it looks, instead of jumping to the middle card first.',
  },
  {
    date: '2026-08-27',
    title: 'Removed the letter badges on the shelf hero',
    body: 'The small two-letter badge next to each row on your dashboard shelf (GM, CM, TC, and so on) is gone — each row already shows its name and accent color, so the badge wasn\'t adding anything.',
  },
  {
    date: '2026-08-27',
    title: 'Fixed: hard-to-read colors in light mode',
    body: 'Owned/Sold badges, the leaderboard\'s gold/silver/bronze podium, and success messages were much lighter than intended if you use light mode — now darker and easier to read. Dark mode was already fine and isn\'t affected.',
  },
  {
    date: '2026-08-26',
    title: 'New: empty states and trophies now speak your language',
    body: 'A comics-only account now sees "your long box," not "your shelf" — same for backlog (games), binder (trading cards), crate (vinyl), and setup (consoles). A few trophies pick up a little flavor line too, once earned.',
    detail: 'Kicks in once you\'ve narrowed down what you collect in Settings > Collecting, or once you\'ve actually got enough of one type logged. Everyone else sees the same copy as before.',
  },
  {
    date: '2026-08-26',
    title: 'Emoji removed site-wide',
    body: 'The colored icon next to each row on your shelf is now a small letter badge instead of an emoji — same color, same spot, just no emoji.',
  },
  {
    date: '2026-08-26',
    title: 'New: public profiles now have their own shelf too',
    body: 'The colorful, per-type shelf your dashboard got recently now shows on your public profile\'s Collection tab too — so anyone visiting sees a shelf shaped like your collection, not a generic one.',
    detail: 'Click a row to filter the collection below to that type, or click a cover to jump straight to it (for games, comics, trading cards, and Funko Pops — other types filter to that row instead).',
  },
  {
    date: '2026-08-26',
    title: 'New: Collection Insights now has widgets made for what you collect',
    body: 'Backlog health and trophy completion for games, raw vs. graded and top sets for trading cards, top series for comics and books, record labels for vinyl/CD, and more — each one only shows up if you actually collect that type.',
    detail: 'All pulled from data you\'ve already logged, no new fields to fill in. Find it under Collection Insights, below the existing breakdowns.',
  },
  {
    date: '2026-08-26',
    title: 'Fixed: Add Item and Quick add now let you add any type again',
    body: 'Picking a type you\'d turned off in Settings > Collecting used to be blocked outright. Now you can always add any type — doing so just checks it back on automatically.',
  },
  {
    date: '2026-08-26',
    title: 'New: your dashboard now has its own shelf, shaped by what you collect',
    body: 'A new shelf at the top of your dashboard shows real cover art from your collection, one row per type you collect, each in its own color. Comics, vinyl, cards — however many types you have, your shelf looks like yours.',
    detail: 'Click a row to filter your collection down to that type, or click a cover to open that item. Only shows types you\'ve enabled in Settings > Collecting, and only once you\'ve actually added something.',
  },
  {
    date: '2026-08-26',
    title: '"Settings" (renamed from "Profile settings"), with a new Collecting tab',
    body: 'The settings panel is now just "Settings" — most of what\'s in there was never really about your profile. A new Collecting tab lets you change which item types you collect any time.',
  },
  {
    date: '2026-08-26',
    title: 'New: tell us what you collect, and we\'ll hide the rest',
    body: 'Signing up now asks which of the 10 item types you actually collect — pick just Comics and Books, say, and everything else disappears from Add Item, Quick add, and the Filters panel. Existing accounts get asked once too, next time you visit.',
    detail: 'Nothing you\'ve already logged is ever hidden — this only trims what you can newly pick from. Change your answer any time from Settings > Collecting, or skip the prompt entirely and nothing changes.',
  },
  {
    date: '2026-08-26',
    title: 'Console search now understands typos',
    body: 'Searching Consoles (Add Item or Quick add) now finds the right one even with a typo or two — "nintendo swithc" still finds Nintendo Switch.',
    detail: 'Games, trading cards, books, movies/music, and comics search a live database that already handles typos on its own, so this was specifically for the built-in console list, which previously needed an exact match.',
  },
  {
    date: '2026-08-26',
    title: 'Fixed: closing Quick add (search) could silently lose your batch',
    body: 'Clicking outside the window (or pressing Escape) used to close it instantly with no warning, even mid-batch. It now asks first if anything\'s queued — clicking to save or add is untouched.',
  },
  {
    date: '2026-08-26',
    title: 'Picking a game with multiple platforms now asks which one',
    body: 'Click a search result released on more than one platform (Add Item or Quick add) and you\'ll get a quick "which platform is this copy for?" choice, instead of the item getting tagged with all of them.',
    detail: 'A result with only one platform still fills in immediately, same as before — this only shows up for titles that were actually released on more than one.',
  },
  {
    date: '2026-08-26',
    title: 'Quick add (search)\'s queue now shows your newest pick at the top',
    body: 'No more scrolling to the bottom to see what you just added — the queue lists newest first.',
  },
  {
    date: '2026-08-26',
    title: 'Game search results now show which platform(s) they cover',
    body: 'Searching a game (in Add Item or Quick add) now shows up to a few platform names next to each result, so you can tell which one you\'re actually about to add.',
  },
  {
    date: '2026-08-26',
    title: 'Quick add (search) now lets you set ownership, condition, and completeness or price',
    body: 'Each item in your batch gets its own small controls before you commit — Ownership and Condition always, plus Completeness for games/consoles or Price for everything else. Search still fills in the rest.',
    detail: 'Defaults to "Owned," no condition, no completeness/price, same as before — nothing changes unless you touch them. Everything else (purchase date, rating, tags) is still set afterward by editing the item.',
  },
  {
    date: '2026-08-26',
    title: 'Barcode scanning removed — search covers it better now',
    body: 'The camera barcode scanner and "Scan multiple" are gone. Search auto-fill (already used by Add Item and Quick add) finds more titles more reliably than a UPC lookup ever did, including older and import releases.',
    detail: 'Your Barcode / UPC field and any barcodes you already had saved aren\'t going anywhere — it\'s just no longer looked up by camera. Use Search or Quick add (search) instead.',
  },
  {
    date: '2026-08-26',
    title: '"+ Add Item" is now a chooser, so Quick add (search) is easier to find',
    body: 'Click "+ Add Item" and pick "Add one item" or "Quick add (search)" — no more digging through More actions to find the bulk-search option.',
  },
  {
    date: '2026-08-26',
    title: '"Quick add (search)" — bulk-add with no spreadsheet, no barcode',
    body: 'Search a title, pick the right result, repeat — then add the whole batch at once. Uses the same auto-fill search the Add form already has for each item type.',
    detail: 'Find it under "+ Add Item" on your dashboard. Review your batch and remove anything before committing — nothing saves until you hit "Add."',
  },
  {
    date: '2026-08-26',
    title: 'A shareable buy link on the gift list',
    body: 'Every item on someone\'s gift list now has "Buy on eBay" and "Search Amazon" links, so whoever\'s shopping for them can go straight to a real place to buy it.',
  },
  {
    date: '2026-08-26',
    title: 'A printable collection appraisal',
    body: 'A new document view of your owned items — grouped by type with subtotals and a total — built for printing or saving as a PDF, useful for insurance documentation.',
    detail: 'Find it in the sidebar under Insights & reports. Each item shows whether its value comes from a purchase price or a checked market price.',
  },
  {
    date: '2026-08-26',
    title: 'Accessibility: keyboard ratings, reduced motion, and a pausable undo',
    body: 'The star rating now supports arrow keys, motion now respects your system\'s "reduce motion" setting, and the delete-undo countdown pauses while you\'re looking at it instead of a fixed 6 seconds.',
    detail: 'Also a new /accessibility page (linked in the footer) laying out what\'s covered today and what\'s still open.',
  },
  {
    date: '2026-08-26',
    title: 'Browse every public list on the site',
    body: 'A new "Lists" page collects every public custom list — Favorites, For sale, whatever people have built — in one browsable directory, not just visible on each owner\'s own profile.',
    detail: 'Click a list to see its full contents on its own page. Linked from the navbar.',
  },
  {
    date: '2026-08-26',
    title: 'See a title\'s crowd rating without opening it',
    body: 'Search results now show the average rating right on the tile (e.g. "4.5★"), not just after you click through to a title\'s page.',
  },
  {
    date: '2026-08-26',
    title: 'Collectors you might like',
    body: 'A new dashboard panel suggests public collectors who rated the same things highly as you did, with a Follow button right on the tile.',
  },
  {
    date: '2026-08-26',
    title: '"For sale" flag for anything you own',
    body: 'Mark an owned item for sale with an asking price, and it shows as a badge on the card wherever it appears — including your public profile.',
  },
  {
    date: '2026-08-26',
    title: 'Your Wrapped — a shareable year in review',
    body: 'A new end-of-year recap card: items added, your busiest month, completions, ratings, and how your collection\'s value changed — built entirely from what you already track.',
    detail: 'Find it in the sidebar under Insights & reports. Step back through past years with the built-in year picker, and screenshot it to share.',
  },
  {
    date: '2026-08-26',
    title: 'More accurate franchise and series completion views',
    body: 'Game franchises, Magic card sets, and comic runs all show more complete, more accurate results now in "See full series."',
    detail: 'Game franchises were quietly capped at a small sample of titles in some cases; Magic and comic series matching wasn\'t finding everything it should have. Both are fixed, and trading card search itself no longer drops real matches for cards with a lot of reprints.',
  },
  {
    date: '2026-08-25',
    title: '"See master set" now works for real for Pokémon trading cards',
    body: 'The Pokémon master-set checklist now pulls genuine per-print variant data (Normal, Reverse Holo, Holo, 1st Edition) instead of missing some of the tiles it should show.',
  },
  {
    date: '2026-08-21',
    title: 'More control over notifications',
    body: 'Mute any of the 5 notification types individually, browse your full notification history (not just the last 30), and filter it down to one type at a time.',
    detail: 'A muted type\'s notifications still exist, they\'re just hidden until you turn that type back on — nothing earned while muted is lost. Find it all in Profile Settings → Notifications and the new "See all notifications" link under the bell.',
  },
  {
    date: '2026-08-21',
    title: 'Gift priority for your wishlist',
    body: 'Mark wishlist items High, Medium, or Low priority so whoever\'s shopping from your gift list knows what to get first.',
    detail: 'Set it per item, or select multiple wishlist items on your dashboard and set (or clear) priority across all of them at once.',
  },
  {
    date: '2026-08-20',
    title: 'A shareable gift list link',
    body: 'A lightweight page showing just your wishlist — perfect for sending to family before a birthday or holiday instead of handing over your whole collection to dig through.',
    detail: 'Reachable from "More actions" on your public profile. A separate toggle in Profile Settings lets you share just this page even if the rest of your collection is private.',
  },
  {
    date: '2026-08-19',
    title: 'Filter your dashboard by tag or list',
    body: 'Click any tag on a card, or pick one of your custom lists, to filter your collection grid down to just that.',
  },
  {
    date: '2026-08-19',
    title: 'Bulk-manage your custom lists',
    body: 'Select multiple items on your dashboard and add (or remove) them all from a custom list at once, instead of one at a time.',
  },
  {
    date: '2026-08-19',
    title: 'Comics get a real master set too',
    body: 'The comics "See master set" checklist now pulls genuine per-issue data for the whole run, including long-running 1000+ issue titles, instead of only knowing about issues someone here happened to log.',
  },
  {
    date: '2026-08-18',
    title: '"On this day" collection memories',
    body: 'Your dashboard now surfaces what you added, finished, or rated on today\'s date in a previous year — when there\'s anything to show.',
  },
  {
    date: '2026-08-18',
    title: 'Dashboard tools, all in one place',
    body: 'Filters, Select mode, Views, and your recommendation panels now live behind a single "Tools" button instead of several separate toggles.',
  },
  {
    date: '2026-08-18',
    title: 'Profile Settings, now organized into tabs',
    body: 'Profile, Notifications, Security, and Data & danger zone — four tabs instead of one long scroll of unrelated settings.',
  },
  {
    date: '2026-08-16',
    title: 'A few real-world fixes',
    body: 'Mobile pages no longer look slightly zoomed in with room to scroll sideways; Add Item now remembers the item type you used last; and CSV import now flags rows that look like duplicates of what you already have.',
  },
  {
    date: '2026-08-16',
    title: 'More accessibility improvements',
    body: 'Icon-only buttons now have real descriptive labels, form fields are properly linked to their labels for screen readers, images have meaningful alt text, and import progress is announced as it happens.',
  },
  {
    date: '2026-08-15',
    title: 'Real password reset, plus sign-out-everywhere',
    body: 'A genuine "Forgot password?" flow on the login page, and a new "Sign out of all other devices" button in Account security for when you\'ve just changed a password you suspect someone else had.',
  },
  {
    date: '2026-08-15',
    title: 'Missing series entries now open a real listing to check',
    body: 'Clicking something you don\'t own yet in a "See full series" grid now opens an actual eBay or CeX search for it, so you can see what filling the gap would cost.',
  },
  {
    date: '2026-08-14',
    title: 'Collection cards: view first, edit as its own step',
    body: 'Clicking a card in your collection now opens a clean detail view — including notes, purchase price, and condition photos, which never had a place to show before — instead of jumping straight into editing.',
    detail: 'Editing is still one click away, either from a small edit button right on the card or from an "Edit" button inside the new detail view.',
  },
  {
    date: '2026-08-14',
    title: '"See full series" now links a missing entry to an eBay check',
    body: 'The full series/set view already greyed out what you don\'t own — clicking one of those now opens a pre-filled Add Item form so you can check what it\'d actually cost you.',
  },
  {
    date: '2026-08-12',
    title: 'Account deletion now has a 48-hour grace period',
    body: 'Deleting your account no longer happens instantly — you get a window to change your mind before anything is actually, permanently removed.',
    detail: 'Confirming account deletion now just schedules it. A banner on your dashboard shows exactly when it\'ll happen, with a one-click "Cancel deletion" button if you sign back in during that window. After 48 hours with no cancellation, the deletion runs for good.',
  },
  {
    date: '2026-08-12',
    title: 'Safer signups — passwords checked against known breaches',
    body: 'Signing up now checks your chosen password against a database of known data breaches and asks for a different one if it\'s been compromised before.',
    detail: 'Only a small, anonymized fragment of your password is ever checked — the real password itself is never sent anywhere or stored in a way that could leak it.',
  },
  {
    date: '2026-08-12',
    title: '"Most valuable" leaderboard now compares fairly across currencies',
    body: 'Rankings for estimated collection value now account for currency instead of just comparing raw numbers.',
    detail: 'A €5,000 collection and a ¥5,000,000 collection used to get ranked as if they were the same size. The ranking now converts behind the scenes to decide order — what actually shows on the leaderboard is still your own currency and your own real total, unchanged.',
  },
  {
    date: '2026-08-11',
    title: 'Pokémon card search is working again',
    body: 'Auto-fill when adding a Pokémon trading card had been quietly broken for a while — it\'s fixed now, running on a different free database.',
    detail: 'The free source this ran on got folded into a paid product with no free tier, so Pokémon searches had been silently coming up empty (Magic: The Gathering search was never affected). Switched to a different free, open database that covers the same ground.',
  },
  {
    date: '2026-08-10',
    title: 'Comics get auto-fill too',
    body: 'A Search button next to Title now auto-fills comic details — cover, series, issue number, writer, artist, and publisher — the same way games and trading cards already work.',
  },
  {
    date: '2026-08-07',
    title: 'Community article & review submissions',
    body: 'Anyone signed in can now write their own review or article for the Reviews & Articles section, not just the Shelf Life team.',
    detail: 'Submissions go through a quick approval step before they\'re published, and you can track your own submission\'s status right on the same page.',
  },
  {
    date: '2026-08-07',
    title: 'A real home page when you\'re signed in, plus Reviews & Articles',
    body: 'Signing in now takes you somewhere actually useful instead of the same "sign up" page everyone else sees — real stats, quick shortcuts, and a new Reviews & Articles section with genuine written content.',
    detail: 'One-tap shortcuts into Add Item, your collection, your profile, Search, Leaderboard, and Shelf mosaic, plus real cover-art discovery rows (Recently added, Recent ratings) pulled from what public collectors across the whole site are doing right now.',
  },
  {
    date: '2026-08-06',
    title: '"See full series" — spot exactly what you\'re missing',
    body: 'Tap any game, comic, trading card, or Funko Pop and hit "See full series" to see the whole franchise or set, with anything you don\'t own greyed out.',
    detail: 'Games use real franchise data; comics, trading cards, and Funko Pops use what other Shelf Life collectors have logged for that same series. Works from your own items and from anyone else\'s public profile too.',
  },
  {
    date: '2026-08-06',
    title: 'Face ID / Touch ID sign-in',
    body: 'A "Sign in with a passkey" option using your device\'s real Face ID, Touch ID, or screen lock — no password typing.',
    detail: 'This is fully verified, not just a biometric-looking button for show — Shelf Life never sees or stores anything biometric, only a secure key. Add one from Profile Settings, then use it right from the login page.',
  },
  {
    date: '2026-08-06',
    title: 'Shelf mosaic',
    body: 'A poster of your real cover art arranged like items standing on a shelf, one wood-plank row per category.',
    detail: 'Browse it live or download/share it as an image. Pick the Whole Shelf, just your Showcase picks, one category, one year you added things in, your Most Valuable items, or hand-pick your own custom selection.',
  },
  {
    date: '2026-08-06',
    title: 'VHS joins the collectible types',
    body: 'VHS tapes are now trackable alongside DVDs, with the same auto-fill Search button.',
  },
  {
    date: '2026-08-06',
    title: 'Combined search, with a detail page for every title',
    body: 'Search now finds collectors and collectible titles at once — click a title to see who owns it, the average rating, and useful links (like time-to-beat and guides for games).',
  },
  {
    date: '2026-08-06',
    title: 'Feedback form',
    body: 'A quick bug report / suggestion form, linked in the footer — no account needed to use it.',
  },
  {
    date: '2026-08-06',
    title: 'Bulk edit',
    body: 'Select multiple items on your dashboard at once to change their status, platform, or tags — or delete them — in one go instead of opening each individually.',
  },
  {
    date: '2026-08-06',
    title: 'Collection Insights',
    body: 'A new stats page beyond the value chart — item counts by type/platform/genre, tracked value by type, spending by month, and your busiest month for adding things.',
  },
  {
    date: '2026-08-06',
    title: 'Condition photos',
    body: 'Attach up to 4 real photos to a physical item, separate from cover art — handy for high-value collectibles where actual condition or grading matters.',
  },
  {
    date: '2026-08-06',
    title: 'Mobile: four cards per row',
    body: 'Your collection grid on phones now shows 4 cards per row in a denser, more scannable layout — tap any card for the full details.',
  },
  {
    date: '2026-08-06',
    title: 'Home page refresh',
    body: 'The home page now shows real card/trophy previews and a live collector count instead of a mockup.',
    detail: 'The sample cards and "Earn real trophies" section render the actual card/trophy components with real data now, so what you see on the home page is exactly what your own dashboard looks like. The collector/item counts next to the main call-to-action are genuinely queried from the database too, not made up.',
  },
  {
    date: '2026-08-06',
    title: 'New logo',
    body: 'A real icon now shows in the navbar, browser tab, and link previews, replacing the old placeholder "S" badge.',
    detail: 'Favicon, Apple touch icon, and the social-share preview image (the thumbnail that shows up when a link gets posted to Discord/Reddit/iMessage/etc.) all use the real icon now too.',
  },
  {
    date: '2026-08-06',
    title: 'Friends-only leaderboard',
    body: 'A new "Friends" tab ranks just the public collectors you follow, with the same 5 categories as the site-wide leaderboard — a smaller, more personal ranking.',
    detail: 'Trophies, most valuable, biggest collection, most-owned, and trending — all scoped to just the people you follow instead of the whole site. It\'s automatically different (and correctly private) per viewer, and shows empty if you\'re signed out.',
  },
  {
    date: '2026-08-06',
    title: 'Saved filter views',
    body: 'Save your search/filters/sort combo as a named shortcut and reapply it with one click.',
    detail: 'A "Views" button next to Filters on the dashboard lets you name and save whatever combination of search/filters/sort you\'ve currently got set up (e.g. "PS5 backlog"), then jump straight back to it later instead of re-picking the same dropdowns every visit. Saved per-device.',
  },
  {
    date: '2026-08-06',
    title: 'Undo on delete',
    body: 'Deleting an item now gives you a few seconds to Undo instead of asking "are you sure?" up front.',
    detail: 'The item disappears immediately when you delete it, but a "Deleted \'X\' — Undo" bar sticks around in the corner for 6 seconds before it\'s actually removed, so an accidental click or a change of mind is recoverable.',
  },
  {
    date: '2026-08-06',
    title: 'Search auto-fill for Books and Consoles',
    body: 'Two more collectible types can now auto-fill from a Search button next to Title, same as games and trading cards.',
    detail: 'Books search Open Library and fill in cover, author, and publisher. Consoles match against a curated list of ~40 common systems and fill in manufacturer and genre (home console/handheld).',
  },
  {
    date: '2026-08-05',
    title: 'Mobile redesign: slide-in menus',
    body: 'The phone nav and the dashboard’s Play Next/Recommended/Value chart panels now live in slide-in drawers instead of stacking down the page.',
    detail: 'On phones, the nav is now a proper slide-in side drawer instead of a dropdown that pushed the whole page down. On the dashboard, the three insight panels that used to stack above your collection now live behind a single "Tools & insights" button, so your item grid is the first thing you see under the stats bar.',
  },
  {
    date: '2026-08-05',
    title: 'Most valuable collections leaderboard',
    body: 'A new leaderboard tab ranks public collectors by estimated collection value.',
    detail: 'Same value blend already used on the dashboard (market price where checked, purchase price otherwise), shown in each collector\'s own currency — a fair ranking within the same currency, not a precise one across different ones.',
  },
  {
    date: '2026-08-05',
    title: 'Funko Pops',
    body: 'A new collectible type — series/line, Pop! #, character, exclusive-to, grade, and Chase variants, right alongside everything else.',
    detail: 'Condition, tags, barcode scanning, and eBay price checks (searching by title + Pop! # for accuracy) all work the same as every other type.',
  },
  {
    date: '2026-08-05',
    title: 'See and refresh other collectors’ prices',
    body: 'Public profiles now show a Collection value stat, and a "Refresh prices" button lets you re-check eBay for someone else’s whole shelf.',
    detail: 'The refresh only ever touches the market-price fields on someone else\'s public items — nothing else about their collection becomes editable.',
  },
  {
    date: '2026-08-05',
    title: 'Consoles',
    body: 'Track your hardware too — Nintendo Switch, PS5, Xbox, retro consoles, and more, right alongside everything else.',
    detail: 'Manufacturer, storage/variant, special edition, region, grade, condition, and completeness fields, plus tags, barcode scanning, and eBay price checks — everything else already works the same way.',
  },
  {
    date: '2026-08-05',
    title: 'eBay price checks use your local site',
    body: 'Based on your currency, prices now come from your local eBay site (ebay.co.uk, ebay.de, etc.) instead of always the US one.',
    detail: 'GBP searches ebay.co.uk, EUR searches ebay.de, CAD searches ebay.ca, AUD searches ebay.com.au, CHF searches ebay.ch, and everything else still searches ebay.com — a rough proxy based on currency rather than a real location lookup.',
  },
  {
    date: '2026-08-05',
    title: 'Smarter, more accurate price checks',
    body: 'Digital items are skipped automatically, and condition now factors into game price searches too.',
    detail: 'Obviously-mismatched listings (lots, bundles, graded copies) get filtered out before pricing, and the "typical" figure is now a median instead of a plain average, so a couple of outlier listings can\'t drag a small sample way up.',
  },
  {
    date: '2026-08-05',
    title: 'Hide digital items',
    body: 'A remembered toggle in Filters to keep your digital library out of the grid.',
    detail: 'Unlike the existing Physical/Digital dropdown filter (which resets every visit), this one stays remembered on your device.',
  },
  {
    date: '2026-08-05',
    title: 'In-app notifications',
    body: 'A bell in the navbar for follows, comments, and new trophies — check it anytime, not just in the moment.',
    detail: 'Opening the bell marks everything read, and the unread count refreshes automatically about once a minute.',
  },
  {
    date: '2026-08-05',
    title: 'Custom lists',
    body: 'Create as many curated sub-lists as you want — Favorites, For sale, whatever — beyond the 5-item showcase.',
    detail: 'Any list with items in it shows up on your public profile alongside the showcase, from a new "Manage lists" button.',
  },
  {
    date: '2026-08-05',
    title: '10 more trophies',
    body: '28 Shelf Life trophies now, up from 18 — new ones for wishlists, variety, following, and more.',
    detail: 'Window Shopping (10 wishlist items), Renaissance Collector (5 item types), Card Shark, Crate Digger, Curator, Social Butterfly, Popular Shelf, Platform Hopper, Half a Thousand, and First Platinum.',
  },
  {
    date: '2026-08-05',
    title: 'Filter/sort by trophy completion %',
    body: 'Find what’s closest to platinum in your backlog, or see everything you haven’t tracked yet.',
    detail: 'A new sort option plus a filter (Platinum only / 75%+ / 50-74% / under 50% / not tracked yet) for your real Xbox/PlayStation completion data.',
  },
  {
    date: '2026-08-04',
    title: 'Compare collections',
    body: "See what you and another collector both own — and what's only in one shelf — with a click from their profile.",
    detail: 'A side-by-side view of what you both own, what only you own, and what only they own, plus a trophy/platinum comparison. Slightly different title formatting still counts as the same item.',
  },
  {
    date: '2026-08-04',
    title: 'Automatic Steam achievement sync',
    body: 'A "Sync achievements" button pulls real completion % straight from Steam for your imported games.',
    detail: 'Walks every Steam-imported game and fills in the same Platinum/completion fields that were previously manual-entry-only, using the same Steam connection already set up for importing your library.',
  },
  {
    date: '2026-08-04',
    title: 'Duplicate warning',
    body: "Adding something you might already own now gets a gentle heads-up before you save.",
    detail: 'Checks your collection as you type and shows a soft "You might already have this" notice for a matching or near-matching title of the same item type — doesn\'t block the save, since a second platform\'s copy is a legitimate reason to "duplicate" something.',
  },
  {
    date: '2026-08-04',
    title: 'Trophies in the activity feed',
    body: 'Landing a trophy now shows up here for your followers too, not just item activity.',
    detail: 'Shows with a small tier-colored badge (bronze/silver/gold/platinum) right alongside adds/completions/ratings.',
  },
  {
    date: '2026-08-04',
    title: 'Leaderboard redesign',
    body: 'Tabs for each ranking plus a gold/silver/bronze podium for the top 3 — including a new Trophy case ranking.',
    detail: 'Trophy case, Biggest collections, Most-owned, and Trending, one at a time instead of all cramped together, with cover art or avatars sized up for the top 3.',
  },
  {
    date: '2026-08-04',
    title: 'Half-star ratings',
    body: 'Rate things in 0.5 steps now — click the left half of a star for a half rating.',
    detail: 'Applies everywhere a rating shows up — item cards, the activity feed, recommendations, and the "Play next" weighting.',
  },
  {
    date: '2026-08-04',
    title: 'Export your collection',
    body: 'Download your whole collection as a spreadsheet any time, as a backup or to move it elsewhere.',
    detail: 'Uses the same column layout as the CSV import template, so it doubles as something you can re-import later if you ever need to.',
  },
  {
    date: '2026-08-04',
    title: 'Xbox/PlayStation trophy tracking',
    body: "Track your real console trophies/achievements per game — separate from Shelf Life's own trophy case.",
    detail: 'A "Platinum\'d" checkbox and a completion % field, kept clearly separate (in both label and appearance) from Shelf Life\'s own collection-milestone trophies. Manual entry — neither platform has a usable API for this.',
  },
  {
    date: '2026-08-04',
    title: '"What should I play next?"',
    body: 'A dashboard pick from your backlog, weighted toward what you already rate highly.',
    detail: 'Pulls from your wishlist instead if nothing\'s backlogged yet, weighted toward the genres/platforms you\'ve already rated 4-5 stars. "Try another" re-rolls without repeating the last pick.',
  },
  {
    date: '2026-08-04',
    title: 'Recommended for you',
    body: "Titles other collectors with similar taste rated highly, that you don't already own.",
    detail: 'A lightweight "people with similar taste to you" match based on shared 4-5 star ratings across public profiles. Click one and it opens Add Item pre-filled with the title, type, and cover art.',
  },
  {
    date: '2026-08-04',
    title: 'Steam account integration',
    body: 'Log in with Steam and import your owned PC games automatically instead of adding them one by one.',
    detail: 'Pick which games to bring in from a checklist — already-imported ones are skipped. Requires your Steam profile\'s "Game details" privacy to be set to Public.',
  },
  {
    date: '2026-08-04',
    title: 'Activity feed',
    body: "See what the collectors you follow have recently added, finished, or rated — right here.",
    detail: 'Only fires for real moments — a first add, newly completing something, rating for the first time — not every incidental edit, and only for people whose profile is public.',
  },
  {
    date: '2026-08-04',
    title: 'Profile showcase',
    body: 'Pin up to 5 favorite items to a featured row at the top of your public profile.',
    detail: 'Pick your favorites and their order from a new "Manage showcase" button — shown with a gold border and "Featured" flag so they stand out from the rest of the grid.',
  },
  {
    date: '2026-08-03',
    title: 'Share your shelf',
    body: 'A one-tap "Share my shelf" button on your profile for sending friends a link to your collection.',
    detail: 'Opens the native share sheet on a phone (Messages, WhatsApp, Mail, etc.); copies your profile link to the clipboard on desktop.',
  },
  {
    date: '2026-08-01',
    title: 'Collection value over time',
    body: "A chart tracking your collection's estimated value across snapshots, so you can watch it grow.",
    detail: 'A snapshot is recorded automatically every time "Refresh all prices" finishes, or manually with a "Record snapshot" button — needs at least two snapshots before a trend line shows up.',
  },
  {
    date: '2026-08-01',
    title: 'Spreadsheet import',
    body: 'Bulk-add items from a CSV file instead of typing each one in by hand.',
    detail: 'Includes a downloadable template with the right columns and an example row per item type, plus a preview of what\'s about to be added and any warnings before it actually imports.',
  },
  {
    date: '2026-07-30',
    title: 'Live eBay price checks',
    body: "Look up an item's current eBay asking price with one click, or refresh your whole collection at once.",
    detail: 'Shows the low/average/high asking price from current active listings (not confirmed sale prices, since eBay doesn\'t offer free access to that data). "Refresh all prices" runs the same check across your whole collection in one go.',
  },
  {
    date: '2026-07-28',
    title: 'Trading cards, vinyl, books, DVDs & CDs',
    body: 'Five more collectible types joined games and comics, each with its own tailored fields.',
    detail: 'Trading cards get set/card number/player/grade; vinyl gets artist/label/format/edition; books, DVDs, and CDs each get their own fitting set of fields too — seven types total at this point.',
  },
  {
    date: '2026-07-20',
    title: 'Trophies',
    body: 'Bronze-to-platinum badges for real collection milestones, shown on your public profile.',
    detail: 'First item, 10/100 items, 25 completed, follower counts, variant hunting, and more — awarded server-side so they can\'t be gamed, shown as a trophy case on your profile.',
  },
];
